openapi: 3.0.0
info:
  title: Next.js Swagger API
  description: A simple API for testing OpenAPI with Next.js.
  version: 1.0.0
paths:
  /api/swagger:
    get:
      summary: Returns a greeting message
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Swagger API Documentation'
    post:
      summary: Receives data and returns it
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'John Doe'
      responses:
        '200':
          description: The received data
          content:
            application/json:
              schema:
                type: object
                properties:
                  received:
                    type: object
                    properties:
                      name:
                        type: string
